import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HiFire } from "react-icons/hi2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main className="bg-gray-200 h-screen flex justify-center items-center">
          <div>
            <div className="flex justify-center mb-10">
              <HiFire color="#f76b8a" size="70" />
            </div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
